export const barcodeSnapshot = {
  data: {
    items: [
      {
        barcode: "070662035016",
        name: "Ramen Noodle Soup",
        brand: "Nissin Foods USA Co Inc",
        ingredients:
          "ENRICHED FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE, RIBOFLAVIN, FOLIC ACID), VEGETABLE OIL (PALM OIL, RICE BRAN OIL), SALT, TEXTURED SOY PROTEIN, CONTAINS LESS THAN 2% OF AUTOLYZED YEAST EXTRACT, BAKER'S YEAST EXTRACT, BEEF FAT, CARAMEL COLOR, CITRIC ACID, CORN SYRUP, DISODIUM GUANYLATE, DISODIUM INOSINATE, DRIED CARROT FLAKE, DRIED CORN, DRIED GREEN ONION, EGG WHITE, GARLIC POWDER, HYDROLYZED CORN PROTEIN, HYDROLYZED SOY PROTEIN, LACTOSE, MONOSODIUM GLUTAMATE, NATURAL FLAVOR, ONION POWDER, POTASSIUM CARBONATE, SODIUM ALGINATE, SODIUM CARBONATE, SODIUM TRIPOLYPHOSPHATE, SPICE, SUGAR, TBHQ (PRESERVATIVE).",
        package: {
          quantity: null,
          size: "100g",
        },
        serving: {
          size: 64,
          measurement_unit: "g",
          size_fulltext: "1 cup",
        },
        categories: ["Other Soups"],
        nutrients: [
          {
            name: "Energy",
            per_100g: 438,
            measurement_unit: "KCAL",
            rank: 300,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Protein",
            per_100g: 10.94,
            measurement_unit: "G",
            rank: 600,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Total lipid (fat)",
            per_100g: 15.62,
            measurement_unit: "G",
            rank: 800,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Carbohydrate, by difference",
            per_100g: 60.94,
            measurement_unit: "G",
            rank: 1110,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Fiber, total dietary",
            per_100g: 4.7,
            measurement_unit: "G",
            rank: 1200,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Sugars, total including NLEA",
            per_100g: 3.12,
            measurement_unit: "G",
            rank: 1510,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Calcium, Ca",
            per_100g: 31,
            measurement_unit: "MG",
            rank: 5300,
            data_points: 0,
            description:
              "Calculated from a daily value percentage per serving size measure",
          },
          {
            name: "Iron, Fe",
            per_100g: 5.62,
            measurement_unit: "MG",
            rank: 5400,
            data_points: 0,
            description:
              "Calculated from a daily value percentage per serving size measure",
          },
          {
            name: "Sodium, Na",
            per_100g: 2125,
            measurement_unit: "MG",
            rank: 5800,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Vitamin C, total ascorbic acid",
            per_100g: 0,
            measurement_unit: "MG",
            rank: 6300,
            data_points: 0,
            description:
              "Calculated from a daily value percentage per serving size measure",
          },
          {
            name: "Vitamin A, IU",
            per_100g: 625,
            measurement_unit: "IU",
            rank: 7500,
            data_points: 0,
            description:
              "Calculated from a daily value percentage per serving size measure",
          },
          {
            name: "Fatty acids, total saturated",
            per_100g: 7.81,
            measurement_unit: "G",
            rank: 9700,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Fatty acids, total monounsaturated",
            per_100g: 6.25,
            measurement_unit: "G",
            rank: 11400,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Fatty acids, total polyunsaturated",
            per_100g: 2.34,
            measurement_unit: "G",
            rank: 12900,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Fatty acids, total trans",
            per_100g: 0,
            measurement_unit: "G",
            rank: 15400,
            data_points: 0,
            description: "Calculated from value per serving size measure",
          },
          {
            name: "Cholesterol",
            per_100g: 0,
            measurement_unit: "MG",
            rank: 15700,
            data_points: 0,
            description:
              "Calculated from a daily value percentage per serving size measure",
          },
        ],
        diet_labels: {
          vegan: {
            name: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            confidence: true,
            confidence_description: "Not compatible with the Vegan diet.",
          },
          vegetarian: {
            name: "Vegetarian",
            is_compatible: false,
            compatibility_level: 0,
            confidence: true,
            confidence_description: "Not compatible with the Vegetarian diet.",
          },
          gluten_free: {
            name: "Gluten Free",
            is_compatible: false,
            compatibility_level: 0,
            confidence: true,
            confidence_description: "Not compatible with the Gluten Free diet.",
          },
        },
        diet_flags: [
          {
            ingredient: "Milk",
            ingredient_description:
              "Not vegan if derived from an animal. Check the ingredients.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: true,
          },
          {
            ingredient: "Eggs",
            ingredient_description:
              "This product contains egg in one form or another. Not vegan friendly.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: true,
          },
          {
            ingredient: "Gluten",
            ingredient_description:
              "Gluten is a general name for the proteins found in different forms of wheat.",
            diet_label: "Gluten Free",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: true,
          },
          {
            ingredient: "Eggs",
            ingredient_description:
              "May contain gluten if used as an ingredient. Some foods add wheat based batter to eggs.",
            diet_label: "Gluten Free",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: true,
          },
          {
            ingredient: "Beef",
            ingredient_description: "Not vegan if originating from cow flesh.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Citric",
            ingredient_description:
              "Emulsifier - May contain animal fat as it is derived from Glycerin/Glycerol.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Disodium",
            ingredient_description:
              "Flavor Enhancer - Often made from animals.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Riboflavin",
            ingredient_description: "May contain milk.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Lactose",
            ingredient_description:
              "Milk sugar. A type of sugar only found in animal milk.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Natural",
            ingredient_description:
              "Ingredients are not synthetic or artificial, but extracted directly from plants or animal products",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Egg",
            ingredient_description:
              "This product contains egg in one form or another. Not vegan friendly.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Caramel",
            ingredient_description:
              "Used as a coloring. Some caramel is derived from cane sugar and not necessarily vegan.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Niacin",
            ingredient_description:
              "Used as a cholesterol treatment. In rare cases it can be derived from animal sources.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Sugar",
            ingredient_description:
              "A sweet material that consists of sucrose. Some sugars are processed through boneblack.",
            diet_label: "Vegan",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Beef",
            ingredient_description:
              "Not a vegetarian friendly option. Beef is taken from the body of a cow.",
            diet_label: "Vegetarian",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Citric",
            ingredient_description:
              "Emulsifier - May contain animal fat as it is derived from Glycerin/Glycerol.",
            diet_label: "Vegetarian",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Disodium",
            ingredient_description:
              "Flavor Enhancer - Often made from animals.",
            diet_label: "Vegetarian",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Natural",
            ingredient_description:
              "Ingredients are not synthetic or artificial, but extracted directly from plants or animal products",
            diet_label: "Vegetarian",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Wheat",
            ingredient_description:
              "Wheat includes gluten. Check the ingredients if gluten-free is not on the label.",
            diet_label: "Gluten Free",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Egg",
            ingredient_description:
              "May contain gluten if used as an ingredient. Some foods add wheat based batter to eggs.",
            diet_label: "Gluten Free",
            is_compatible: null,
            compatibility_level: 1,
            compatibility_description:
              "Not necessarily banned. Consider the source of each ingredient.",
            is_allergen: false,
          },
          {
            ingredient: "Gelatin",
            ingredient_description:
              "Protein obtained by boiling animal skin, connective tissue or bones, usually from cows or pigs.",
            diet_label: "Vegan",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
          {
            ingredient: "Gelatin",
            ingredient_description:
              "Protein obtained by boiling animal skin, connective tissue or bones, usually from cows or pigs.",
            diet_label: "Vegetarian",
            is_compatible: false,
            compatibility_level: 0,
            compatibility_description:
              "Banned - Not acceptable for diet/lifestyle.",
            is_allergen: false,
          },
        ],
        packaging_photos: {
          front: {
            small: null,
            thumb: null,
            display: null,
          },
          nutrition: {
            small: null,
            thumb: null,
            display: null,
          },
          ingredients: {
            small: null,
            thumb: null,
            display: null,
          },
        },
        allergens: ["Eggs", "Gluten", "Milk"],
        brand_list: ["Nissin", "Nissin Foods USA Co Inc"],
        countries: ["United States"],
        country_details: {
          english_speaking: 1,
          non_english_speaking: 0,
        },
        palm_oil_ingredients: [],
        ingredient_list: [
          "Autolyzed Yeast Extract",
          "Baker S Yeast Extract",
          "Beef Fat",
          "Canola Oil",
          "Caramel Color",
          "Citric Acid",
          "Contains Less Than 2 Of Dried Carrot Flake",
          "Corn Syrup",
          "Disodium Guanylate",
          "Disodium Inosinate",
          "Dried Corn",
          "Dried Green Pea",
          "Enriched Wheat Flour",
          "Folic Acid",
          "Garlic Powder",
          "Gelatin",
          "Hydrolyzed Corn Protein",
          "Hydrolyzed Soy Protein",
          "Hydrolyzed Wheat Protein",
          "Monosodium Glutamate",
          "Natural Flavor",
          "Niacin",
          "Onion Powder",
          "Palm Oil",
          "Partially Hydrogenated Cottonseed And Soybean Oil",
          "Potassium Carbonate",
          "Powdered Beef",
          "Preservative",
          "Reduced Iron",
          "Riboflavin",
          "Rice Bran Oil",
          "Salt",
          "Sodium Alginate",
          "Sodium Carbonate",
          "Sodium Tripolyphosphate",
          "Soy Sauce",
          "Soybean",
          "Sugar",
          "Tbhq",
          "Textured Soy Protein",
          "Thiamine Mononitrate",
          "Vegetable Oil",
          "Water",
          "Wheat",
          "Wheat Flour",
        ],
        has_english_ingredients: true,
        minerals: ["Potassium Carbonate", "Reduced Iron", "Sodium Carbonate"],
        vitamins: ["Folic Acid", "Niacin", "Riboflavin"],
        traces: [],
        description: "RAMEN NOODLE SOUP",
        keywords: ["Meal", "Nissin", "Noodle", "Ramen", "Soup"],
      },
    ],
  },
};

/* -------------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------------- */

export const yo = {
  id: 23232,
  original: "steaks",
  originalName: "steaks",
  name: "steaks",
  amount: 1.0,
  unit: "",
  unitShort: "",
  unitLong: "",
  possibleUnits: ["steak", "piece", "g", "oz", "serving"],
  estimatedCost: { value: 501.72, unit: "US Cents" },
  consistency: "solid",
  shoppingListUnits: ["ounces", "pounds"],
  aisle: "Meat",
  image: "ribeye-raw.jpg",
  meta: [],
  nutrition: {
    nutrients: [
      { title: "Vitamin B3", name: "Vitamin B3", amount: 11.06, unit: "mg" },
      { title: "Folic Acid", name: "Folic Acid", amount: 0.0, unit: "µg" },
      { title: "Iron", name: "Iron", amount: 3.89, unit: "mg" },
      { title: "Carbohydrates", name: "Carbohydrates", amount: 0.0, unit: "g" },
      { title: "Vitamin C", name: "Vitamin C", amount: 0.0, unit: "mg" },
      { title: "Vitamin A", name: "Vitamin A", amount: 33.9, unit: "IU" },
      {
        title: "Mono Unsaturated Fat",
        name: "Mono Unsaturated Fat",
        amount: 15.31,
        unit: "g",
      },
      { title: "Caffeine", name: "Caffeine", amount: 0.0, unit: "mg" },
      { title: "Phosphorus", name: "Phosphorus", amount: 325.44, unit: "mg" },
      { title: "Sodium", name: "Sodium", amount: 117.52, unit: "mg" },
      { title: "Vitamin D", name: "Vitamin D", amount: 0.23, unit: "µg" },
      { title: "Protein", name: "Protein", amount: 45.47, unit: "g" },
      { title: "Vitamin B6", name: "Vitamin B6", amount: 0.9, unit: "mg" },
      {
        title: "Poly Unsaturated Fat",
        name: "Poly Unsaturated Fat",
        amount: 1.56,
        unit: "g",
      },
      { title: "Selenium", name: "Selenium", amount: 55.14, unit: "µg" },
      { title: "Sugar", name: "Sugar", amount: 0.0, unit: "g" },
      { title: "Fiber", name: "Fiber", amount: 0.0, unit: "g" },
      { title: "Vitamin B12", name: "Vitamin B12", amount: 3.75, unit: "µg" },
      { title: "Vitamin B1", name: "Vitamin B1", amount: 0.2, unit: "mg" },
      {
        title: "Net Carbohydrates",
        name: "Net Carbohydrates",
        amount: 0.0,
        unit: "g",
      },
      { title: "Calories", name: "Calories", amount: 470.08, unit: "kcal" },
      { title: "Calcium", name: "Calcium", amount: 15.82, unit: "mg" },
      { title: "Copper", name: "Copper", amount: 0.18, unit: "mg" },
      { title: "Vitamin B2", name: "Vitamin B2", amount: 0.54, unit: "mg" },
      {
        title: "Saturated Fat",
        name: "Saturated Fat",
        amount: 14.22,
        unit: "g",
      },
      { title: "Vitamin K", name: "Vitamin K", amount: 3.39, unit: "µg" },
      { title: "Alcohol", name: "Alcohol", amount: 0.0, unit: "g" },
      { title: "Zinc", name: "Zinc", amount: 11.59, unit: "mg" },
      { title: "Folate", name: "Folate", amount: 6.78, unit: "µg" },
      { title: "Fat", name: "Fat", amount: 31.96, unit: "g" },
      { title: "Potassium", name: "Potassium", amount: 605.68, unit: "mg" },
      { title: "Magnesium", name: "Magnesium", amount: 47.46, unit: "mg" },
      { title: "Cholesterol", name: "Cholesterol", amount: 137.86, unit: "mg" },
    ],
    properties: [
      {
        name: "Glycemic Index",
        title: "Glycemic Index",
        amount: 0.0,
        unit: "",
      },
      { name: "Glycemic Load", title: "Glycemic Load", amount: 0.0, unit: "" },
    ],
    flavonoids: [
      { name: "Cyanidin", title: "Cyanidin", amount: 0.0, unit: "" },
      { name: "Petunidin", title: "Petunidin", amount: 0.0, unit: "" },
      { name: "Delphinidin", title: "Delphinidin", amount: 0.0, unit: "" },
      { name: "Malvidin", title: "Malvidin", amount: 0.0, unit: "" },
      { name: "Pelargonidin", title: "Pelargonidin", amount: 0.0, unit: "" },
      { name: "Peonidin", title: "Peonidin", amount: 0.0, unit: "" },
      { name: "Catechin", title: "Catechin", amount: 0.0, unit: "" },
      {
        name: "Epigallocatechin",
        title: "Epigallocatechin",
        amount: 0.0,
        unit: "",
      },
      { name: "Epicatechin", title: "Epicatechin", amount: 0.0, unit: "" },
      {
        name: "Epicatechin 3-gallate",
        title: "Epicatechin 3-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Epigallocatechin 3-gallate",
        title: "Epigallocatechin 3-gallate",
        amount: 0.0,
        unit: "",
      },
      { name: "Theaflavin", title: "Theaflavin", amount: 0.0, unit: "" },
      { name: "Thearubigins", title: "Thearubigins", amount: 0.0, unit: "" },
      { name: "Eriodictyol", title: "Eriodictyol", amount: 0.0, unit: "" },
      { name: "Hesperetin", title: "Hesperetin", amount: 0.0, unit: "" },
      { name: "Naringenin", title: "Naringenin", amount: 0.0, unit: "" },
      { name: "Apigenin", title: "Apigenin", amount: 0.0, unit: "" },
      { name: "Luteolin", title: "Luteolin", amount: 0.0, unit: "" },
      { name: "Isorhamnetin", title: "Isorhamnetin", amount: 0.0, unit: "" },
      { name: "Kaempferol", title: "Kaempferol", amount: 0.0, unit: "" },
      { name: "Myricetin", title: "Myricetin", amount: 0.0, unit: "" },
      { name: "Quercetin", title: "Quercetin", amount: 0.0, unit: "" },
      {
        name: "Theaflavin-3,3'-digallate",
        title: "Theaflavin-3,3'-digallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3'-gallate",
        title: "Theaflavin-3'-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3-gallate",
        title: "Theaflavin-3-gallate",
        amount: 0.0,
        unit: "",
      },
      { name: "Gallocatechin", title: "Gallocatechin", amount: 0.0, unit: "" },
    ],
    caloricBreakdown: {
      percentProtein: 38.74,
      percentFat: 61.26,
      percentCarbs: 0.0,
    },
    weightPerServing: { amount: 226, unit: "g" },
  },
  categoryPath: ["beef", "red meat", "meat"],
};

/* -------------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------------- */

export const pinapple = {
  id: 9266,
  original: "pineapples",
  originalName: "pineapples",
  name: "pineapples",
  amount: 1.0,
  unit: "",
  unitShort: "",
  unitLong: "",
  possibleUnits: ["piece", "slice", "fruit", "g", "oz", "cup", "serving"],
  estimatedCost: { value: 299.0, unit: "US Cents" },
  consistency: "solid",
  shoppingListUnits: ["pieces"],
  aisle: "Produce",
  image: "pineapple.jpg",
  meta: [],
  nutrition: {
    nutrients: [
      { title: "Vitamin B3", name: "Vitamin B3", amount: 4.53, unit: "mg" },
      { title: "Folic Acid", name: "Folic Acid", amount: 0.0, unit: "µg" },
      { title: "Iron", name: "Iron", amount: 2.62, unit: "mg" },
      {
        title: "Carbohydrates",
        name: "Carbohydrates",
        amount: 118.74,
        unit: "g",
      },
      { title: "Vitamin C", name: "Vitamin C", amount: 432.59, unit: "mg" },
      { title: "Vitamin A", name: "Vitamin A", amount: 524.9, unit: "IU" },
      { title: "Vitamin B5", name: "Vitamin B5", amount: 1.93, unit: "mg" },
      {
        title: "Mono Unsaturated Fat",
        name: "Mono Unsaturated Fat",
        amount: 0.12,
        unit: "g",
      },
      { title: "Caffeine", name: "Caffeine", amount: 0.0, unit: "mg" },
      { title: "Phosphorus", name: "Phosphorus", amount: 72.4, unit: "mg" },
      { title: "Sodium", name: "Sodium", amount: 9.05, unit: "mg" },
      { title: "Vitamin D", name: "Vitamin D", amount: 0.0, unit: "µg" },
      { title: "Protein", name: "Protein", amount: 4.89, unit: "g" },
      { title: "Vitamin B6", name: "Vitamin B6", amount: 1.01, unit: "mg" },
      {
        title: "Poly Unsaturated Fat",
        name: "Poly Unsaturated Fat",
        amount: 0.36,
        unit: "g",
      },
      { title: "Selenium", name: "Selenium", amount: 0.91, unit: "µg" },
      { title: "Choline", name: "Choline", amount: 49.78, unit: "mg" },
      { title: "Sugar", name: "Sugar", amount: 89.14, unit: "g" },
      { title: "Fiber", name: "Fiber", amount: 12.67, unit: "g" },
      { title: "Vitamin B12", name: "Vitamin B12", amount: 0.0, unit: "µg" },
      { title: "Vitamin B1", name: "Vitamin B1", amount: 0.71, unit: "mg" },
      {
        title: "Net Carbohydrates",
        name: "Net Carbohydrates",
        amount: 106.07,
        unit: "g",
      },
      { title: "Calories", name: "Calories", amount: 452.5, unit: "kcal" },
      { title: "Calcium", name: "Calcium", amount: 117.65, unit: "mg" },
      { title: "Manganese", name: "Manganese", amount: 8.39, unit: "mg" },
      { title: "Copper", name: "Copper", amount: 1.0, unit: "mg" },
      { title: "Vitamin B2", name: "Vitamin B2", amount: 0.29, unit: "mg" },
      {
        title: "Saturated Fat",
        name: "Saturated Fat",
        amount: 0.08,
        unit: "g",
      },
      { title: "Vitamin K", name: "Vitamin K", amount: 6.34, unit: "µg" },
      { title: "Alcohol", name: "Alcohol", amount: 0.0, unit: "g" },
      { title: "Zinc", name: "Zinc", amount: 1.09, unit: "mg" },
      { title: "Folate", name: "Folate", amount: 162.9, unit: "µg" },
      { title: "Fat", name: "Fat", amount: 1.09, unit: "g" },
      { title: "Potassium", name: "Potassium", amount: 986.45, unit: "mg" },
      { title: "Magnesium", name: "Magnesium", amount: 108.6, unit: "mg" },
      { title: "Cholesterol", name: "Cholesterol", amount: 0.0, unit: "mg" },
      { title: "Vitamin E", name: "Vitamin E", amount: 0.18, unit: "mg" },
    ],
    properties: [
      {
        name: "Glycemic Index",
        title: "Glycemic Index",
        amount: 58.67,
        unit: "",
      },
      {
        name: "Glycemic Load",
        title: "Glycemic Load",
        amount: 62.23,
        unit: "",
      },
    ],
    flavonoids: [
      { name: "Cyanidin", title: "Cyanidin", amount: 0.0, unit: "mg" },
      { name: "Petunidin", title: "Petunidin", amount: 0.0, unit: "mg" },
      { name: "Delphinidin", title: "Delphinidin", amount: 0.0, unit: "mg" },
      { name: "Malvidin", title: "Malvidin", amount: 0.0, unit: "mg" },
      { name: "Pelargonidin", title: "Pelargonidin", amount: 0.0, unit: "mg" },
      { name: "Peonidin", title: "Peonidin", amount: 0.0, unit: "mg" },
      { name: "Catechin", title: "Catechin", amount: 0.0, unit: "mg" },
      {
        name: "Epigallocatechin",
        title: "Epigallocatechin",
        amount: 0.0,
        unit: "mg",
      },
      { name: "Epicatechin", title: "Epicatechin", amount: 0.0, unit: "mg" },
      {
        name: "Epicatechin 3-gallate",
        title: "Epicatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      {
        name: "Epigallocatechin 3-gallate",
        title: "Epigallocatechin 3-gallate",
        amount: 0.0,
        unit: "mg",
      },
      { name: "Theaflavin", title: "Theaflavin", amount: 0.0, unit: "" },
      { name: "Thearubigins", title: "Thearubigins", amount: 0.0, unit: "" },
      { name: "Eriodictyol", title: "Eriodictyol", amount: 0.0, unit: "" },
      { name: "Hesperetin", title: "Hesperetin", amount: 0.0, unit: "mg" },
      { name: "Naringenin", title: "Naringenin", amount: 0.0, unit: "mg" },
      { name: "Apigenin", title: "Apigenin", amount: 0.0, unit: "mg" },
      { name: "Luteolin", title: "Luteolin", amount: 0.09, unit: "mg" },
      { name: "Isorhamnetin", title: "Isorhamnetin", amount: 0.0, unit: "" },
      { name: "Kaempferol", title: "Kaempferol", amount: 0.0, unit: "mg" },
      { name: "Myricetin", title: "Myricetin", amount: 0.09, unit: "mg" },
      { name: "Quercetin", title: "Quercetin", amount: 1.27, unit: "mg" },
      {
        name: "Theaflavin-3,3'-digallate",
        title: "Theaflavin-3,3'-digallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3'-gallate",
        title: "Theaflavin-3'-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Theaflavin-3-gallate",
        title: "Theaflavin-3-gallate",
        amount: 0.0,
        unit: "",
      },
      {
        name: "Gallocatechin",
        title: "Gallocatechin",
        amount: 0.0,
        unit: "mg",
      },
    ],
    caloricBreakdown: {
      percentProtein: 3.88,
      percentFat: 1.94,
      percentCarbs: 94.18,
    },
    weightPerServing: { amount: 905, unit: "g" },
  },
  categoryPath: ["tropical fruit", "fruit"],
};
