import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  // Settings Home Styles
  userContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  headerContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    width: '100%',
    height: '20%',
    marginLeft: '5%',
  },
  headerText: {
    fontSize: 20,
    color: '#343a40',
    fontWeight: 'bold',
    marginLeft: '2%',
  },
  headerEmail: {
    fontSize: 18,
    color: '#343a40',
    marginLeft: '2%',
  },
  bodyContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '70%',
    width: '100%',
  },
  settingsTextHeader: {
    fontSize: 16,
    color: '#343a40',
    marginLeft: '3%',
    marginBottom: '1%',
  },
  settingsBtn: {
    height: '25%',
    width: '100%',
    backgroundColor: '#e5e5e5',
    flexDirection: 'row',
    paddingLeft: '3%',
    paddingRight: '5%',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 0.5,
  },
  settingsDetail: {
    width: '70%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  settingsText: {
    fontSize: 18,
    marginLeft: '5%',
  },
  settingSectionContainer: {
    height: '50%',
    width: '100%',
  },
  signOutBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D54C4C',
    borderRadius: 15,
    height: '6%',
    width: '70%',
  },
  btnText: {
    color: 'white',
    fontWeight: 'bold',
  },
  // Edit User Details Styles
  userBodyContainer: {
    height: '50%',
    width: '80%',
    justifyContent: 'space-evenly',
    alignItems: 'flex-start',
  },
  inputContainer: {
    height: '40%',
    width: '100%',
    justifyContent: 'space-evenly',
  },
  inputStyle: {
    height: '30%',
    width: '100%',
    padding: 10,
    textAlign: 'left',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 15,
  },
  submitBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#D54C4C',
    borderRadius: 15,
    height: '5%',
    width: '60%',
  },
  // Edit Allergies Container
  alContainer: {
    flex: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
  },
  alCheckboxContainer: {
    flex: 4,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: '10%',
    height: '80%',
    width: '100%',
  },
  alCheckboxItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '80%',
    height: '7%',
    borderBottomWidth: 1,
  },
  alCheckboxDetail: {
    fontSize: 20,
  },
  alButtonContainer: {
    height: '6%',
    width: '85%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '10%',
  },
  alSubmitButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    height: '100%',
    backgroundColor: '#4C956C',
    borderRadius: 20,
    marginBottom: '10%',
    marginRight: '2%',
    marginLeft: '2%',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  // Change Email
  emContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  emInputContainer: {
    height: '20%',
    width: '80%',
    justifyContent: 'space-evenly',
  },
  emInputStyle: {
    height: '30%',
    width: '100%',
    padding: 10,
    textAlign: 'left',
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 15,
  },
  emSubmitContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '20%',
    width: '80%',
  },
  emSubmitBtn: {
    height: '27%',
    width: '90%',
    borderRadius: 20,
    backgroundColor: '#4C956C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emErrorMsg: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#D54C4C',
  },
});

export default styles;
